function getId() {
    let urlParams = new URLSearchParams(window.location.search);
    let id = urlParams.get('id')
    return id;

}

let trainerData = [{
        // louis vuitton start
        id: 1,
        imgSrc: './assets/louisvuitton/l1.png',
        name: "Louis Vuitton Neverfull MM",
        details: "The Neverfull MM, a timeless tote adorned in signature monogram canvas, seamlessly blends style and functionality. With its spacious interior and durable leather handles, this iconic handbag is perfect for daily essentials and more. It's an accessible luxury piece for those who appreciate both fashion and practicality.",
        price: " Price:$850"
    },
    {
        id: 2,
        imgSrc: './assets/louisvuitton/l2.jpg',
        name: "Louis Vuitton Alma BB",
        details: "   The Alma BB exudes sophistication in its compact design and classic monogram canvas. Perfect for on-the-go elegance, this chic handbag balances practicality with a timeless aesthetic. It's an affordable luxury accessory for those who appreciate refined simplicity.",
        price: " Price:$780"

    },
    {
        id: 3,
        imgSrc: './assets/louisvuitton/l3.png',
        name: "Louis Vuitton Pochette Metis",
        details: "Elevate your style with the Pochette Metis, a chic crossbody bag crafted in monogram canvas. Its sleek design, thoughtful organization, and versatile wearability make it a go-to accessory for both day and night. It's an elegant yet accessible piece for the modern fashion enthusiast.",
        price: " Price:$950",
    },
    {
        id: 4,
        imgSrc: './assets/louisvuitton/l4.jpg',
        name: "Louis Vuitton Speedy 25",
        details: "The Speedy 25, dressed in iconic monogram canvas, is a compact masterpiece that seamlessly fuses fashion with everyday usability. Its enduring style, sturdy structure, and just-right size make it a must-have for those who appreciate luxury on the go. It's an affordable statement piece.",
        price: " Price:$890",
    },
    {
        id: 5,
        imgSrc: './assets/louisvuitton/l5.jpg',
        name: "Louis Vuitton Favourite MM",
        details: "Charm with the Favourite MM, a versatile clutch in monogram canvas that adds a touch of glamour to any ensemble. Its spacious interior, stylish design, and detachable strap make it a perfect companion for day or night. It's an accessible luxury essential for the modern woman",
        price: " Price:$920",
    },
    {
        id: 6,
        imgSrc: './assets/louisvuitton/l6.jpg',
        name: "Louis Vuitton Montaigne MM",
        details: "Step into sophistication with the Montaigne MM, a spacious shoulder bag dressed in monogram canvas. Its refined elegance, thoughtful organization, and enduring style make it a timeless addition to your collection. It's a luxury statement within reach.",
        price: " Price:$980",
    },
    {
        id: 7,
        imgSrc: './assets/louisvuitton/l7.jpg',
        name: "Louis Vuitton Artsy MM",
        details: "The Artsy MM, a hobo bag in monogram canvas, effortlessly blends style and comfort. Its spacious design, artistic silhouette, and supple leather handle make it a chic choice for everyday wear. It's a statement piece that complements your individuality with accessible luxury.",
        price: " Price:$950",
    },
    {
        id: 8,
        imgSrc: './assets/louisvuitton/l8.jpg',
        name: "Louis Vuitton Croisette",
        details: "Effortless elegance defines the Croisette, a compact handbag in monogram canvas. Its simplicity, stylish appeal, and versatility make it an ideal choice for those who appreciate refined simplicity. It's luxury made accessible for the modern fashion enthusiast.",
        price: " Price:$890",
    },
    {
        id: 9,
        imgSrc: './assets/louisvuitton/l9.jpg',
        name: "Louis Vuitton Graceful MM",
        details: "Discover grace with the Graceful MM, a hobo bag in monogram canvas that strikes the perfect balance between fashion and functionality. Its slouchy silhouette, spacious interior, and comfortable shoulder strap make it an essential accessory for everyday elegance. It's an affordable luxury choice.",
        price: " Price:$920",
    },
    {
        id: 10,
        imgSrc: './assets/louisvuitton/l10.jpg',
        name: "Louis Vuitton Keepall 45",
        details: "The Keepall 45, an iconic travel companion in monogram canvas, is the epitome of style and practicality. Its spacious interior, sturdy leather handles, and timeless design make it a must-have for the modern jet-setter. It's an accessible luxury for those who appreciate travel in fashion.",
        price: " Price:$980",
    },
    {
        id: 11,
        imgSrc: './assets/louisvuitton/l11.png',
        name: "Louis Vuitton NeoNoe",
        details: "Add a touch of modern flair to your collection with the NeoNoe, a bucket bag in monogram canvas. Its trendy silhouette, vibrant color, and adjustable strap make it a versatile and stylish accessory. It's an affordable luxury piece for the contemporary fashionista.",
        price: " Price:$950",
    },
    {
        id: 12,
        imgSrc: './assets/louisvuitton/l12.jpeg',
        name: "Louis Vuitton Speedy 35",
        details: "The Speedy 35, adorned in iconic monogram canvas, is a spacious handbag that seamlessly fuses fashion with practicality. Its classic design, ample storage, and sturdy structure make it a timeless addition to your wardrobe. It's luxury within reach.",
        price: " Price:$920",
    },
    {
        id: 13,
        imgSrc: './assets/louisvuitton/l13.jpg',
        name: "Louis Vuitton Pallas Clutch",
        details: "Upgrade your evening look with the Pallas Clutch, a stylish accessory in monogram canvas. Its compact design, feminine details, and detachable chain strap make it a versatile choice for special occasions. It's an accessible luxury essential for elegant evenings.",
        price: " Price:$890",
    },
    {
        id: 14,
        imgSrc: './assets/louisvuitton/l14.jpg',
        name: "Louis Vuitton Neverfull PM",
        details: "Effortless style meets affordability with the Neverfull PM, a small tote in monogram canvas. Perfect for everyday elegance, its compact size, and iconic design make it a versatile choice. It's an accessible luxury piece for the modern woman.",
        price: " Price:$780",
    },
    {
        id: 15,
        imgSrc: './assets/louisvuitton/l15.jpg',
        name: "Louis Vuitton Delightful MM",
        details: "Discover delight with the Delightful MM, a hobo bag in monogram canvas that combines practicality with timeless elegance. Its slouchy silhouette, spacious interior, and comfortable shoulder strap make it an everyday luxury. It's an affordable statement piece.",
        price: " Price:$950",
    },

    {
        id: 16,
        imgSrc: '/assets/louisvuitton/l16.png',
        name: "Louis Vuitton Pochette Accessories",
        details: "Elevate your look with the Pochette Accessories, a compact accessory in monogram canvas. Its sleek design, versatile use, and iconic print make it a chic addition to any ensemble. It's an affordable luxury touch.",
        price: " Price:$650",
    },
    {
        id: 17,
        imgSrc: './assets/louisvuitton/l17.jpg',
        name: "Louis Vuitton Turenne PM",
        details: "Step into elegance with the Turenne PM, a medium-sized handbag in monogram canvas. Its refined design, thoughtful organization, and enduring style make it a sophisticated accessory. It's luxury within reach.",
        price: " Price:$920",
    },
    {
        id: 18,
        imgSrc: './assets/louisvuitton/l18.jpg',
        name: "Louis Vuitton Speedy 40",
        details: "Experience spacious luxury with the Speedy 40, a handbag in iconic monogram canvas. Its ample storage, classic design, and durable structure make it a stylish yet practical choice. It's an accessible statement piece.",
        price: " Price:$980",
    },
    {
        id: 19,
        imgSrc: './assets/louisvuitton/l19.jpg',
        name: "Louis Vuitton Favorite PM",
        details: "Charm with the Favorite PM, a compact clutch in monogram canvas, ideal for adding a touch of luxury to any outfit. Its versatile design, sleek silhouette, and detachable strap make it a must-have accessory. It's an affordable luxury essential.",
        price: " Price:$780",
    },
    {
        id: 20,
        imgSrc: './assets/louisvuitton/l20.jpg',
        name: "Louis Vuitton Eva Clutch",
        details: "Make a statement with the Eva Clutch, a versatile accessory in monogram canvas that complements any look. Its compact size, iconic print, and detachable strap make it a chic addition to your collection. It's an affordable luxury touch.",
        price: " Price:$650",
    },
    {
        id: 21,
        imgSrc: './assets/louisvuitton/l21.jpg',
        name: "Louis Vuitton Speedy 20",
        details: "Discover compact luxury with the Speedy 20, a small handbag in iconic monogram canvas. Perfect for on-the-go style, its petite size and classic design make it a versatile accessory. Priced at $850, it's an affordable statement piece.",
        price: " Price:$850",
    },
    {
        id: 22,
        imgSrc: './assets/louisvuitton/l22.jpg',
        name: "Louis Vuitton Favorite GM",
        details: "Embrace versatility with the Favorite GM, a larger clutch in monogram canvas that makes a bold yet affordable statement. Its spacious interior, sleek silhouette, and detachable strap make it a chic accessory. It's luxury within reach.",
        price: " Price:$980",
    },
    {
        id: 23,
        imgSrc: './assets/louisvuitton/l23.jpg',
        name: "Louis Vuitton Artsy GM",
        details: "Make a statement with the Artsy GM, a spacious hobo bag in monogram canvas that adds a touch of glamour to any ensemble. Its artistic silhouette, comfortable shoulder strap, and iconic print make it a bold yet affordable choice. It's a luxury statement within reach.",
        price: " Price:$950",
    },
    {
        id: 24,
        imgSrc: './assets/louisvuitton/l24.png',
        name: "Louis Vuitton Palm Springs Mini",
        details: "Step into the trendy with the Palm Springs Mini, a mini backpack in monogram canvas that offers both style and practicality. Its compact size, modern design, and iconic print make it a chic addition to your collection. It's an affordable luxury accessory.",
        price: " Price:$780",
    },
    {
        id: 25,
        imgSrc: './assets/louisvuitton/l25.jpg',
        name: "Louis Vuitton Palermo PM",
        details: "Elevate your style with the Palermo PM, a medium-sized handbag in monogram canvas, perfect for the modern woman. Its versatile design, refined silhouette, and enduring style make it a sophisticated accessory and it's luxury within reach.",
        price: " Price:$920",
    },
    {
        id: 26,
        imgSrc: './assets/louisvuitton/l26.jpg',
        name: "Louis Vuitton Tivoli PM",
        details: "Discover timeless elegance with the Tivoli PM, a medium-sized handbag in monogram canvas that exudes sophistication. Its classic design, thoughtful organization, and enduring style make it a chic accessory. It's an affordable luxury choice.",
        price: " Price:$890",
    },
    {
        id: 27,
        imgSrc: './assets/louisvuitton/l27.jpg',
        name: "Louis Vuitton Tuileries",
        details: "Step into sophistication with Tuileries, a stylish handbag in monogram canvas that makes a bold yet affordable statement. Its sleek design, vibrant details, and iconic print make it a chic addition to your collection. It's luxury within reach.",
        price: " Price:$950",
    },
    {
        id: 28,
        imgSrc: './assets/louisvuitton/l28.png',
        name: "Louis Vuitton Marly Dragonne",
        details: "Charm with the Marly Dragonne, a clutch with a wrist strap in monogram canvas, ideal for evening occasions. Its compact size, feminine details, and detachable strap make it a versatile accessory. It's an affordable luxury essential.",
        price: " Price:$780",


    },
    {
        id: 29,
        imgSrc: './assets/louisvuitton/l29.jpg',
        name: "Louis Vuitton Babylone",
        details: "Elevate your look with the Babylone, a hobo bag in monogram canvas that effortlessly combines style and practicality. Its slouchy silhouette, spacious interior, and comfortable shoulder strap make it a chic accessory. It's luxury within reach.",
        price: " Price:$920",


    },
    {
        id: 30,
        imgSrc: './assets/louisvuitton/l30.jpg',
        name: "Louis Vuitton Lumineuse PM",
        details: "Discover luminosity with the Lumineuse PM, a stylish tote in monogram canvas, offering both elegance and functionality. Its refined design, thoughtful organization, and enduring style make it a sophisticated accessory. It's an affordable luxury choice.",
        price: " Price:$950",
    },

    {
        id: 31,
        imgSrc: './assets/louisvuitton/l31.jpg',
        name: "Louis Vuitton Sperone BB",
        details: "Chic meets affordability with the Sperone BB, a small backpack in monogram canvas. Its compact size, modern design, and adjustable straps make it a stylish yet practical choice. It's an accessible luxury piece for the contemporary fashionista.",
        price: " Price:$850",
    },
    {
        id: 32,
        imgSrc: './assets/louisvuitton/l32.png',
        name: "Louis Vuitton Tivoli GM",
        details: "Experience luxury with the Tivoli GM, a large handbag in monogram canvas that makes a bold yet timeless statement. Its spacious interior, classic design, and durable structure make it a stylish yet practical choice. It's an accessible luxury for the modern woman.",
        price: " Price:$980",
    },
    {
        id: 33,
        imgSrc: './assets/louisvuitton/l33.jpg',
        name: "Louis Vuitton Musette Tango",
        details: "Make a statement with the Musette Tango, a crossbody bag in monogram canvas that adds a touch of luxury to any ensemble. Its compact size, versatile design, and iconic print make it a chic addition to your collection. It's an affordable luxury touch.",
        price: " Price:$650",
    },
    {
        id: 34,
        imgSrc: './assets/louisvuitton/l34.png',
        name: "Louis Vuitton Speedy 45",
        details: "Discover spacious luxury with the Speedy 45, a handbag in iconic monogram canvas that combines style and practicality. Its ample storage, classic design, and durable structure make it a versatile accessory. It's an accessible statement piece.",
        price: " Price:$890",
    },
    {
        id: 35,
        imgSrc: './assets/louisvuitton/l35.png',
        name: "Louis Vuitton Neverfull GM",
        details: "Effortless style meets affordability with the Neverfull GM, a large tote in monogram canvas. Perfect for everyday luxury, its spacious interior and iconic design make it a versatile choice. It's an accessible luxury piece for the modern woman.",
        price: " Price:$950",
    },
    {
        id: 36,
        imgSrc: './assets/louisvuitton/l36.png',
        name: "Louis Vuitton Trevi PM",
        details: "Step into sophistication with the Trevi PM, a medium-sized handbag in monogram canvas, making an elegant statement. Its refined design, thoughtful organization, and enduring style make it a chic accessory. It's luxury within reach.",
        price: " Price:$920",
    },
    {
        id: 37,
        imgSrc: './assets/louisvuitton/l37.jpg',
        name: "Louis Vuitton Berkeley",
        details: "Charm with the Berkeley, a medium-sized handbag in monogram canvas that effortlessly combines style and practicality. Its classic design, ample storage, and enduring style make it a versatile accessory. It's an affordable luxury piece.",
        price: " Price:$780",
    },
    {
        id: 38,
        imgSrc: './assets/louisvuitton/l38.png',
        name: "Louis Vuitton Delightful GM",
        details: "Discover delight with the Delightful GM, a larger hobo bag in monogram canvas that adds a touch of luxury to your everyday look. Its slouchy silhouette, spacious interior, and comfortable shoulder strap make it an essential accessory. It's a statement piece within reach.",
        price: " Price:$950",
    },
    {
        id: 39,
        imgSrc: './assets/louisvuitton/l39.png',
        name: "Louis Vuitton Bloomsbury PM",
        details: "Elevate your style with the Bloomsbury PM, a medium-sized messenger bag in monogram canvas that offers both flair and functionality. Its versatile design, ample storage, and iconic print make it a chic addition to your collection. It's an affordable luxury touch.",
        price: " Price:$890",
    },
    {
        id: 40,
        imgSrc: './assets/louisvuitton/l40.png',
        name: "Louis Vuitton Pallas Chain",
        details: "Experience luxury on a budget with the Pallas Chain, a versatile chain bag in monogram canvas that adds a touch of glamour to any outfit. Its compact size, stylish design, and detachable strap make it a chic accessory. It's an accessible yet prestigious addition.",
        price: " Price:$980",
    },
    // louis vuitton end

    
    // gucci starts
    {
        id: 41,
        imgSrc: './assets/gucci/g1.png',
        name: "Gucci Marmont Mini Matelassé",
        details: " The Marmont Mini Matelassé, a chic crossbody adorned with the signature GG logo, exudes modern glamour. Compact yet spacious, this purse is perfect for on-the-go essentials. The matelassé leather adds a luxurious texture, making it an ideal accessory for those who appreciate style without compromising practicality",
        price: "Price:$950",
    },
    {
        id: 42,
        imgSrc: './assets/gucci/g2.png',
        name: "Gucci Soho Disco",
        details: "  The Soho Disco, a compact and stylish crossbody, is crafted with soft, pebbled leather. Its distinctive interlocking GG logo and tassel detail make it a playful yet timeless accessory. Ideal for both day and night, this purse seamlessly combines fashion and functionality.",
        price: " Price:$780",
    },

    {
        id: 43,
        imgSrc: './assets/gucci/g3.png',
        name: "Gucci Ophidia Small Shoulder Bag",
        details: " Embrace vintage-inspired elegance with the Ophidia Small Shoulder Bag. Featuring the iconic Web stripe and GG Supreme canvas, this a structured purse is a sophisticated addition to your collection.The gold- toned hardware adds a touch of opulence, making it a statement piece.",
        price: " Price:$890",

    },
    {
        id: 44,
        imgSrc: './assets/gucci/g4.png',
        name: "    Gucci Bamboo Shopper Tote",
        details: " Elevate your style with the Bamboo Shopper Tote, a classic Gucci design known for its bamboo handles. The spacious interior and versatile silhouette make it a perfect companion for everyday activities. Impeccably crafted, this tote is a symbol of timeless luxury.",
        price: " Price:$960",
    },
    {
        id: 45,
        imgSrc: './assets/gucci/g5.png',
        name: "Gucci GG Marmont Super Mini",
        details: " Discover the charm of the GG Marmont Super Mini, a petite yet impactful accessory. The quilted leather and iconic GG logo create a distinctive look. Wear it as a crossbody or belt bag, showcasing your fashion-forward sense with this versatile piece.",
        price: " Price:$580",
    },
    {
        id: 46,
        imgSrc: './assets/gucci/g6.jpeg',
        name: " Gucci Jackie 1961 Hobo Bag",
        details: "Pay homage to a fashion icon with the Jackie 1961 Hobo Bag. The equestrian-inspired design, coupled with the signature piston closure, reflects Gucci's heritage. The supple leather and spacious interior make it a stylish and practical choice for any occasion.",
        price: " Price:$920",
    },
    {
        id: 47,
        imgSrc: './assets/gucci/g7.png',
        name: " Gucci Rajah Large Tote",
        details: "   Make a bold statement with the Rajah Large Tote, adorned with the striking crystal tiger head. The combination of smooth leather and the GG Supreme canvas creates a luxurious contrast. This tote is an expression of modern glamor and undeniable sophistication",
        price: " Price:$950",
    },
    {
        id: 48,
        imgSrc: './assets/gucci/g8.png',
        name: " Gucci Arli Medium Shoulder Bag",
        details: "   Embrace a retro-inspired vibe with the Arli Medium Shoulder Bag. The double G hardware and structured shape nod to Gucci's archival designs. Crafted from smooth leather, this bag exudes timeless elegance, making it a versatile addition to your collection.",
        price: " Price:$820",
    },
    {
        id: 49,
        imgSrc: './assets/gucci/g9.png',
        name: " Gucci GG Marmont Mini Chain Wallet",
        details: "   Elevate your evening look with the GG Marmont Mini Chain Wallet. The chevron pattern and the iconic GG logo make a subtle yet impactful statement. This compact wallet seamlessly transitions into a chic crossbody, perfect for a night out on the town. ",
        price: " Price:$690",
    },
    {
        id: 50,
        imgSrc: '="./assets/gucci/g10.png',
        name: "  Gucci Zumi Small Top Handle Bag",
        details: "  Experience modern sophistication with the Zumi Small Top Handle Bag. Named after actress and musician Zumi Rosow, this bag features a mix of smooth and grainy leather. The interlocking G and Horsebit hardware add a touch of glamor, making it a standout accessory.        ",
        price: " Price:$980",
    },
    {
        id: 51,
        imgSrc: "./assets/gucci/g11.png",
        name: " Gucci Broadway Velvet Clutch",
        details: "Embrace opulence with the Broadway Velvet Clutch, a luxurious evening accessory. The soft velvet is adorned with crystal embellishments and the interlocking G detail. This clutch adds a touch of vintage-inspired glamor to any formal ensemble. ",
        price: " Price:$750",
    },
    {
        id: 52,
        imgSrc: 'assets/gucci/g12.png',
        name: "Gucci Sylvie Mini Chain Bag",
        details: "Step into elegance with the Sylvie Mini Chain Bag, featuring the iconic grosgrain ribbon and gold-toned chain. The structured silhouette and buckle closure showcase a perfect blend of classic and contemporary design, making it a timeless accessory ",
        price: " Price:$890",
    },
    {
        id: 53,
        imgSrc: './assets/gucci/g13.png',
        name: " Gucci Ophidia Mini Round Shoulder Bag",
        details: "Add a touch of vintage flair to your look with the Ophidia Mini Round Shoulder Bag.The GG Supreme canvas, red and green Web stripe, and textured leather create a harmonious design.This compact bag is a playful nod to Gucci's heritage.",
        price: "Price:$730",
    },
    {
        id: 54,
        imgSrc: './assets/gucci/g14.png',
        name: " Gucci Dionysus Super Mini Bag",
        details: "Make a statement with the Dionysus Super Mini Bag, featuring the distinctive tiger head closure. The combination of textured and smooth leather adds dimension to this compact accessory. Carry it as a clutch or wear it crossbody for a versatile style. ",
        price: " Price:$580",
    },
    {
        id: 55,
        imgSrc: './assets/gucci/g15.jpg',
        name: " Gucci Marmont Small Matelassé Shoulder Bag",
        details: "Elevate your ensemble with the Marmont Small Matelassé Shoulder Bag, adorned with the signature GG logo. The quilted leather and antique gold-toned hardware exude sophistication. This shoulder bag seamlessly transitions from day to night.",
        price: " Price:$920",
    },
    {
        id: 56,
        imgSrc: './assets/gucci/g16.png',
        name: " Gucci Neo Vintage GG Supreme Messenger Bag",
        details: "Embrace a casual yet stylish vibe with the Neo Vintage GG Supreme Messenger Bag. The monogram canvas and leather trims create a distinctive look. The adjustable strap and multiple pockets make it a practical choice for everyday use. ",
        price: " Price:$860",
    },
    {
        id: 57,
        imgSrc: './assets/gucci/g17.png',
        name: "Gucci Queen Margaret Quilted Leather Backpack",
        details: "Make a fashion-forward statement with the Queen Margaret Quilted Leather Backpack. The bee motif and pearl embellishments add a whimsical touch to the quilted leather. This backpack is a perfect blend of luxury and playfulness.",
        price: "Price:$980",
    },

    {
        id: 58,
        imgSrc: './assets/gucci/g18.png',
        name: " Gucci GG Psychedelic Small Tote",
        details: "Dive into the vibrant world of the GG Psychedelic Small Tote, featuring a colorful interpretation of the GG motif. The contrasting leather details and playful design make it a standout piece. This tote is perfect for those who embrace bold and eclectic styles.",
        price: "Price:4950",
    },
    {
        id: 59,
        imgSrc: './assets/gucci/g19.png',
        name: "Gucci Padlock GG Supreme Shoulder Bag",
        details: "Secure your style with the Padlock GG Supreme Shoulder Bag, adorned with a gold-toned padlock closure. The GG Supreme canvas and leather trims create a timeless and versatile accessory. Carry it by the top handle or use the detachable shoulder strap for added convenience. ",
        price: " Price:$890",
    },
    {
        id: 60,
        imgSrc: './assets/gucci/g20.png',
        name: "Gucci Broadway Leather Clutch",
        details: " Unleash your inner glamor with the Broadway Leather Clutch, featuring a dazzling crystal bow. The smooth leather and gold-toned hardware add a touch of sophistication. This clutch is a perfect companion for special occasions and evenings out.",
        price: "Price:$720",
    },
    {
        id: 61,
        imgSrc: './assets/gucci/g21.png',
        name: " Gucci GG Marmont Velvet Belt Bag",
        details: " Embrace a touch of luxury with the GG Marmont Velvet Belt Bag. The plush velvet and the iconic GG logo create a sumptuous look. Wear it around your waist or sling it across your chest for a trendy and practical accessory.",
        price: " Price:$780 ",
    },
    {
        id: 62,
        imgSrc: './assets/gucci/g22.png',
        name: " Gucci Arli Small Shoulder Bag:",
        details: "Elevate your everyday style with the Arli Small Shoulder Bag, featuring the double G hardware and a compact silhouette. Crafted from smooth leather, this bag exudes modern sophistication. The adjustable shoulder strap adds versatility to your look.",
        price: " Price:$850",
    },
    {
        id: 63,
        imgSrc: './assets/gucci/g23.png',
        name: "Gucci GG Supreme Monogram Pouch:",
        details: "Simplify your essentials with the GG Supreme Monogram Pouch, a sleek and minimalist accessory. The monogram canvas and leather trim create a timeless design. Carry it as a clutch or use it to organize your larger bag.",
        price: "Price:$420",
    },
    {
        id: 64,
        imgSrc: './assets/gucci/g24.png',
        name: "Gucci Rajah Mini Crossbody Bag:",
        details: " Make a bold statement with the Rajah Mini Crossbody Bag, adorned with the crystal tiger head. The combination of smooth leather and the GG Supreme canvas creates a luxurious contrast. This crossbody bag is perfect for those who love to stand out.",
        price: " Price:$690",
    },
    {
        id: 65,
        imgSrc: './assets/gucci/g25.png',
        name: "Gucci Zumi Mini Shoulder Bag:",
        details: "Experience modern elegance with the Zumi Mini Shoulder Bag, named after Zumi Rosow. The mix of smooth and grainy leather, along with the interlocking G and Horsebit hardware, creates a sophisticated and versatile accessory.",

        price: "Price:$920",
    },
    {
        id: 66,
        imgSrc: './assets/gucci/g26.png',
        name: "Gucci Jackie 1961 Bucket Bag:",
        details: "Embrace the bucket bag trend with the Jackie 1961 Bucket Bag. The equestrian-inspired design and the signature piston closure capture the essence of Gucci's heritage. The supple leather and spacious interior make it a stylish and practical choice.",
        price: "Price:$890 ",
    },
    {
        id: 67,
        imgSrc: './assets/gucci/g27.png',
        name: "Gucci Marmont Matelassé Leather Wallet:",
        details: "Add a touch of luxury to your accessories with the Marmont Matelassé Leather Wallet. The quilted leather and the iconic GG logo make a statement. The organized interior ensures you carry your essentials in style.",
        price: "Price:$550 ",
    },
    {
        id: 68,
        imgSrc: './assets/gucci/g28.png',
        name: "Gucci Ophidia GG Supreme Belt Bag ",
        details: " Embrace a sporty-chic look with the Ophidia GG Supreme Belt Bag. The monogram canvas, green and red Web stripe, and leather trim create a dynamic design. Wear it around your waist or as a crossbody for a versatile style.",
        price: "Price:$620",
    },
    {
        id: 69,
        imgSrc: './assets/gucci/g29.png',
        name: " Gucci Dionysus Mini Chain Wallet",
        details: "Elevate your evening ensemble with the Dionysus Mini Chain Wallet, featuring the tiger head closure. The combination of textured and smooth leather adds a tactile element to this compact and glamorous accessory.",
        price: " Price:$780 ",
    },
    {
        id: 70,
        imgSrc: './assets/gucci/g30.png',
        name: " Gucci Broadway Crystal-Embellished Clutch",
        details: " Unleash your inner glamor with the Broadway Crystal-Embellished Clutch, featuring a dazzling crystal tiger head. The smooth leather and gold-toned hardware add a touch of opulence. This clutch is a show-stopping addition to your formal attire.",

        price: "Price:$950",
    },
    {
        id: 71,
        imgSrc: './assets/gucci/g31.png',
        name: " Gucci Neo Vintage GG Supreme Tote",
        details: " Embrace a timeless look with the Neo Vintage GG Supreme Tote, featuring the monogram canvas and leather trims. The spacious interior and classic design make it a versatile and practical choice for everyday use.",
        price: " Price:$880",
    },
    {
        id: 72,
        imgSrc: './assets/gucci/g32.jpeg',
        name: " Gucci Marmont Velvet Chevron Shoulder Bag:",
        details: "Experience luxury with the Marmont Velvet Chevron Shoulder Bag, adorned with a quilted chevron pattern. The plush velvet and the iconic GG logo create a sumptuous and sophisticated look. This shoulder bag is perfect for adding a touch of glamor to your ensemble.",
        price: " Price:$830 ",
    },

    {
        id: 73,
        imgSrc: './assets/gucci/g33.png',
        name: "Gucci Rajah Small Shoulder Bag ",
        details: "Make a statement with the Rajah Small Shoulder Bag, adorned with the crystal tiger head. The combination of smooth leather and the GG Supreme canvas creates a luxurious contrast. This shoulder bag is a perfect blend of bold design and refined elegance.",
        price: " Price:$960",
    },
    {
        id: 74,
        imgSrc: './assets/gucci/g34.png"',
        name: "Gucci Ophidia GG Supreme Card Case",
        details: "Simplify your essentials with the Ophidia GG Supreme Card Case, featuring the monogram canvas and leather trim. The compact design fits easily into your pocket or small handbag, making it a stylish and practical accessory.",
        price: "Price:$320 ",
    },
    {
        id: 75,
        imgSrc: './assets/gucci/g35.png',
        name: "Gucci Zumi Leather Card Holder",
        details: "Elevate your daily essentials with the Zumi Leather Card Holder, named after Zumi Rosow. The mix of smooth and grainy leather, along with the interlocking G and Horsebit hardware, creates a sophisticated and compact accessory.",
        price: "Price:$260",
    },
    {
        id: 76,
        imgSrc: './assets/gucci/g36.png',
        name: "Gucci GG Marmont Matelassé Camera Bag:",
        details: "Add a touch of luxury to your casual look with the GG Marmont Matelassé Camera Bag. The quilted leather and the iconic GG logo make a statement. The compact size is perfect for carrying your essentials with ease.",
        price: "Price:$720",
    },
    {
        id: 77,
        imgSrc: './assets/gucci/g37.png',
        name: "Gucci Arli Large Top Handle Bag",
        details: "Make a bold statement with the Arli Large Top Handle Bag, featuring the double G hardware and a spacious silhouette. Crafted from smooth leather, this bag exudes modern sophistication. The top handle and detachable shoulder strap add versatility to your look.",
        price: " Price:$980 ",
    },
    {
        id: 78,
        imgSrc: './assets/gucci/g38.png"',
        name: " Gucci Rajah Velvet Mini Bag",
        details: "Embrace a touch of luxury with the Rajah Velvet Mini Bag, adorned with the crystal tiger head. The plush velvet and the GG Supreme canvas create a sumptuous and stylish look. This mini bag is perfect for adding a pop of glamor to your ensemble.",
        price: " Price:$590 ",
    },
    {
        id: 79,
        imgSrc: './assets/gucci/g39.png',
        name: " Gucci Dionysus GG Blooms Card Case:",
        details: "Add a floral touch to your essentials with the Dionysus GG Blooms Card Case, featuring the iconic GG motif with a blooming pattern. The compact design and vibrant print make it a stylish and functional accessory.",
        price: " Price:$350 ",
    },
    {
        id: 80,
        imgSrc: './assets/gucci/g40.png',
        name: "Gucci Broadway Leather Shoulder Bag",
        details: " Unleash your inner glamour with the Broadway Leather Shoulder Bag, featuring a dazzling crystal bow. The smooth leather and gold-toned hardware add a touch of opulence. This shoulder bag is a perfect companion for special occasions and evenings out. ",
        price: "Price:$890",
    },

    //gucci ends

    // prada starts
 {
    id: 81,
    imgSrc: './assets/prada/p1.png',
    name: "Prada Opulence Evening Clutch",
    details: "  Elevate your evening ensemble with the Prada Opulence Evening Clutch. Crafted with meticulous attention to detail, this compact clutch is adorned with the iconic Prada logo, radiating sophistication and glamour. The sleek silhouette is perfect for formal events, and the interior is surprisingly spacious, accommodating all your essentials with style. ",
    price: " Price:$750",
},
{
    id: 82,
    imgSrc: './assets/prada/p2.png',
    name: "Prada Metropolitan Tote Mini",
    details: " Embrace the urban chic with the Prada Metropolitan Tote Mini. Designed for the modern cosmopolitan woman, this tote seamlessly blends style and practicality. The contemporary design is complemented by durable materials, ensuring it stands up to the hustle and bustle of daily life. A must-have for those who appreciate fashion on the go",
    price: " Price:$890",
},
{
    id: 83,
    imgSrc: './assets/prada/p3.png',
    name: "Prada Celestial Luna Crossbody   ",
    details: "Unleash your celestial charm with the Prada Celestial Luna Crossbody. This crossbody bag is a fusion of contemporary style and cosmic allure. The unique design, paired with an adjustable strap, offers versatility for various occasions. It's a stellar choice for those who want to make a statement while staying effortlessly chic.",
    price: " Price:$980",
},
{
    id: 84,
    imgSrc: './assets/prada/p4.jpg',
    name: " Prada Harmony Hobo Bliss:",
    details: "Find harmony between style and comfort with the Prada Harmony Hobo Bliss. The slouchy silhouette and supple leather create an effortlessly elegant look. Perfect for a casual day out, this hobo bag embodies relaxation without compromising on sophistication, making it an essential addition to your collection.",
    price: " Price:$850",
},
{
    id: 85,
    imgSrc: './assets/prada/p5.jpg',
    name: "Prada Mirage Elegance Shoulder Bag: ",
    details: " Make a bold statement with the Prada Mirage Elegance Shoulder Bag. Capturing attention with its daring design and impeccable craftsmanship, this shoulder bag is an emblem of confident fashion. With enough space for your essentials, it's a striking accessory that seamlessly blends luxury and contemporary allure.",
    price: " Price:$920",
},
{
    id: 86,
    imgSrc: './assets/prada/p6.jpg',
    name: ".Prada Saffiano Delight Wallet:",
    details: "Embrace the refined elegance of the Prada Saffiano Delight Wallet. Crafted for the modern minimalist, this delicate accessory features ample card slots and a sleek silhouette. The Saffiano leather adds a touch of sophistication, making it the perfect choice for those who value both style and practicality in their everyday essentials.",
    price: " Price:$650",
},
{
    id: 87,
    imgSrc: './assets/prada/p7.png',
    name: "Prada Essence Casual Bucket Bag:",
    details: " Experience casual elegance with the Prada Essence Casual Bucket Bag. The relaxed shape and premium materials make this bag a versatile companion for a day of shopping or a casual brunch with friends. Effortlessly chic, it strikes the perfect balance between laid-back style and luxury.",
    price: " Price:$780",
},

{
    id: 88,
    imgSrc: './assets/prada/p8.png',
    name: " Prada Nova Vibrance Clutch: ",
    details: "Infuse a pop of color into your ensemble with the Prada Nova Vibrance Clutch. The compact size and vibrant design make it an ideal accessory for adding personality to your look. Whether you're heading to a social gathering or a night out, this clutch is a playful and stylish choice.",
    price: " Price:$550",
},
{
    id: 89,
    imgSrc: './assets/prada/p9.png',
    name: "Prada Serenity Explorer Backpack:",
    details: "Navigate your day with the Prada Serenity Explorer Backpack. This backpack seamlessly blends functionality with high fashion, featuring multiple compartments and adjustable straps. Ideal for those on the go, it ensures you stay stylish while accommodating all your essentials with ease.",
    price: " Price:$970",
},
{
    id: 90,
    imgSrc: './assets/prada/p10.jpg',
    name: "Prada Galleria Mini Elegance Tote",
    details: " Embrace timeless elegance with the Prada Galleria Mini Elegance Tote. This downsized classic exudes sophistication with its structured design and iconic Prada detailing. The mini size adds a touch of casual versatility, making it a staple for any fashion-forward individual.",
    price: " Price:$980",
},
{
    id: 91,
    imgSrc: './assets/prada/p11.jpg',
    name: "Prada Regal Velvet Gala Clutch:    ",
    details: "Dazzle at your next soirée with the Prada Regal Velvet Gala Clutch. Crafted from luxurious velvet, this clutch exudes opulence. The intricate detailing and compact design make it a regal choice for special occasions, offering both style and sophistication.",
    price: " Price:980",
},
{
    id: 92,
    imgSrc: './assets/prada/p12.jpg',
    name: "Prada Renaissance Leather Satchel:",
    details: "Step into a new era of fashion with the Prada Renaissance Leather Satchel. The combination of timeless design and premium leather creates a bag that transcends trends. Spacious and versatile, it's a symbol of enduring style for the modern woman.",
    price: " Price:$960",
},
{
    id: 93,
    imgSrc: './assets/prada/p13.jpg',
    name: "  Prada Twilight Rose Crossbody: ",
    details: "Embrace the allure of twilight with the Prada Twilight Rose Crossbody. The delicate rose motif on rich leather adds a touch of romance to your ensemble. Compact yet practical, this crossbody is perfect for those who appreciate the poetic side of fashion.",
    price: " Price:$750",
},
{
    id: 94,
    imgSrc: './assets/prada/p14.png',
    name: "Prada Urban Edge Backpack:",
    details: "Navigate the urban landscape in style with the Prada Urban Edge Backpack. Its sleek design and durable materials make it a practical yet fashionable choice for city living. The multiple compartments ensure you're ready for anything the day brings.",
    price: " Price:$920",
},
{
    id: 95,
    imgSrc: './assets/prada/p15.jpg',
    name: "Prada Luxe Affair Shoulder Bag:    ",
    details: "Indulge in luxury with the Prada Luxe Affair Shoulder Bag. The exquisite craftsmanship and attention to detail make it a standout accessory. Whether you're heading to a gala or a high-profile event, this shoulder bag is a testament to your refined taste.",
    price: " Price:$980",
},
{
    id: 96,
    imgSrc: './assets/prada/p16.jpg',
    name: "Prada Refined Elegance Wallet:   ",
    details: "Elevate your daily essentials with the Prada Refined Elegance Wallet. Crafted with precision and style, this wallet features a timeless design and practical layout. The Saffiano leather adds a touch of sophistication, making it a must-have for the discerning fashionista.",
    price: " Price:$620",
},
{
    id: 97,
    imgSrc: './assets/prada/p17.png',
    name: "Prada Seraphic Crossbody Bliss:  ",
    details: "Channel celestial vibes with the Prada Seraphic Crossbody Bliss. The angelic design and compact size make it an ethereal accessory for day or night. This crossbody effortlessly combines style with a touch of heavenly charm",
    price: " Price:$980",
},
{
    id: 98,
    imgSrc: './assets/prada/p18.png',
    name: "Prada Pinnacle Elegance Tote:",
    details: "Reach the pinnacle of style with the Prada Pinnacle Elegance Tote. The structured design and premium materials create an accessory that commands attention. Versatile and chic, it's an essential for the modern woman on the go.",
    price: " Price:$840",
},
{
    id: 99,
    imgSrc: './assets/prada/p19.png',
    name: "Prada Whispering Breeze Clutch:    ",
    details: "Let the wind of fashion carry you with the Prada Whispering Breeze Clutch. The lightweight design and playful details make it an ideal choice for a casual day out. This clutch is a breath of fresh air in the world of accessories",
    price: " Price:$550",
},
{
    id: 100,
    imgSrc: './assets/prada/p20.jpg',
    name: "  Prada Quilted Harmony Hobo: ",
    details: "Wrap yourself in the comfort of style with the Prada Quilted Harmony Hobo. The quilted pattern and supple leather create a cozy yet chic look. This hobo bag is perfect for those who value both fashion and ease in their daily lives.",
    price: " Price:$870",
},
{
    id: 101,
    imgSrc: './assets/prada/p21.jpg',
    name: "Prada Enchanting Sequin Satchel: ",
    details: "Unleash your inner enchantress with the Prada Enchanting Sequin Satchel. The dazzling sequins create a mesmerizing effect, making this satchel a showstopper at any event. With its spacious interior and chic design, it's a celebration of glamour and elegance.",
    price: " Price:$960",
},
{
    id: 102,
    imgSrc: './assets/prada/p22.jpg',
    name: "Prada Midnight Muse Crossbody:   ",
    details: "Embrace the mystery of the night with the Prada Midnight Muse Crossbody. The deep, rich hues and compact design make it a versatile companion for evening affairs. This crossbody is a testament to Prada's commitment to sophistication and modern allure.",
    price: " Price:$780",
},

{
    id: 103,
    imgSrc: './assets/prada/p23.jpg',
    name: "Prada Everlasting Elegance Tote: ",
    details: "Discover timeless beauty with the Prada Everlasting Elegance Tote. Its classic silhouette and meticulous detailing showcase the brand's dedication to enduring style. Whether at work or play, this tote is a symbol of perpetual sophistication.",
    price: " Price:$920",
},
{
    id: 104,
    imgSrc: './assets/prada/p24.png',
    name: " Prada Cityscape Explorer Backpack:    ",
    details: "Conquer the urban landscape with the Prada Cityscape Explorer Backpack. The city-inspired design and functional layout make it an ideal companion for your daily adventures. Stay organized without compromising on style with this urban explorer.",
    price: " Price:$890",
},
{
    id: 105,
    imgSrc: './assets/prada/p25.png',
    name: " Prada Velvet Whispers Clutch:  ",
    details: "Soft to the touch, the Prada Velvet Whispers Clutch is a tactile delight. The plush velvet and understated design make it a versatile accessory for various occasions. Elevate your style with this chic and refined clutch.",
    price: " Price:$650",
},
{
    id: 106,
    imgSrc: './assets/prada/p26.png',
    name: "Prada Cosmic Serenity Wallet:   ",
    details: " Reach for the stars with the Prada Cosmic Serenity Wallet. The celestial-inspired design and compact size make it a whimsical addition to your daily essentials. This wallet is a perfect blend of style and cosmic charm.",
    price: " Price:$620",
},
{
    id: 107,
    imgSrc: './assets/prada/p27.jpeg',
    name: "   Prada Tranquil Breeze Crossbody: ",
    details: "Let the Prada Tranquil Breeze Crossbody transport you to a serene state of style. The breezy design and calming colors make it an ideal choice for casual outings. This crossbody is a breath of fresh air in the fast-paced world of fashion.",
    price: " Price:$880",
},
{
    id: 108,
    imgSrc: './assets/prada/p28.jpg',
    name: "Prada Sublime Leather Elegance:",
    details: "Immerse yourself in sublime luxury with the Prada Sublime Leather Elegance. The exquisite leather and sophisticated design make it a statement piece. Elevate your ensemble with this embodiment of opulence.",
    price: " Price:$980",
},
{
    id: 109,
    imgSrc: './assets/prada/p29.jpg',
    name: "Prada Mosaic Muse Tote:  ",
    details: "Become a muse of fashion with the Prada Mosaic Muse Tote. The mosaic-inspired design and spacious interior make it a practical yet stylish choice. This tote is a work of art for the modern woma",
    price: " Price:$840",
},
{
    id: 110,
    imgSrc: './assets/prada/p30.png',
    name: " Prada Essence of Dawn Clutch:",
    details: "Capture the essence of a new day with the Prada Essence of Dawn Clutch. The delicate design and vibrant colors make it a symbol of renewal and style. Start your day right with this cheerful and chic clutch.",
    price: " Price:$550",
},
{
    id: 111,
    imgSrc: './assets/prada/p31.jpg',
    name: "Prada Starlit Gala Satchel:  ",
    details: " Shine like a star with the Prada Starlit Gala Satchel. The celestial details and structured silhouette make it an elegant choice for any occasion. This satchel is a constellation of style in the vast universe of fashion.",
    price: " Price:960",
},
{
    id: 112,
    imgSrc: './assets/prada/p32.png',
    name: " Prada Sunset Bliss Crossbody: ",
    details: " Witness the beauty of a sunset with the Prada Sunset Bliss Crossbody. The warm hues and compact design make it an ideal companion for evening strolls. This crossbody captures the essence of a picturesque twilight.",
    price: " Price:$780",
},
{
    id: 113,
    imgSrc: './assets/prada/p33.jpg',
    name: "   Prada Modern Muse Tote: ",
    details: "Embrace modernity with the Prada Modern Muse Tote. Its contemporary design and functional features cater to the needs of the modern woman. This tote is a fusion of style and practicality for the fashion-forward. ",
    price: " Price:$920",
},
{
    id: 114,
    imgSrc: './assets/prada/p34.png',
    name: "Prada Aurora Explorer Backpack:",
    details: "Embark on a journey with the Prada Aurora Explorer Backpack. The aurora-inspired design and spacious compartments make it a whimsical yet practical accessory. Illuminate your daily adventures with this backpack.",
    price: " Price:$890",
},
{
    id: 115,
    imgSrc: './assets/prada/p35.png',
    name: "Prada Whispering Petals Clutch:",
    details: "  Carry a bouquet of style with the Prada Whispering Petals Clutch. The floral details and compact size make it a delightful accessory for various occasions. This clutch is a garden of elegance in the world of fashion.",
    price: " Price:$650",
},
{
    id: 116,
    imgSrc: './assets/prada/p36.png',
    name: " Prada Ethereal Serenity Wallet: ",
    details: " Experience ethereal charm with the Prada Ethereal Serenity Wallet. The delicate design and compact form make it a graceful addition to your daily essentials. This wallet is a touch of otherworldly elegance.",
    price: " Price:$620",
},
{
    id: 117,
    imgSrc: './assets/prada/p37.jpg',
    name: " Prada Enigma Explorer Crossbody: ",
    details: "Unravel the enigma of fashion with the Prada Enigma Explorer Crossbody. The mysterious design and adjustable strap make it an intriguing choice for day or night. This crossbody is a puzzle of style waiting to be solved.",
    price: " Price:$880",
},
{
    id: 118,
    imgSrc: './assets/prada/p38.png',
    name: "Prada Urban Verve Elegance:",
    details: "  Infuse your style with urban verve using the Prada Urban Verve Elegance. The sleek design and premium materials create an accessory that exudes confidence and sophistication. Elevate your look with this embodiment of city chic.",
    price: " Price:$980",
},
{
    id: 119,
    imgSrc: './assets/prada/p39.png',
    name: "Prada Mirage Dreams Tote: ",
    details: "Chase your dreams with the Prada Mirage Dreams Tote. The dreamy design and spacious interior make it a practical yet whimsical choice. This tote is a canvas for your aspirations in the world of fashion.",
    price: " Price:$840",
},
{
    id: 120,
    imgSrc: './assets/prada/p40.png',
    name: "*Prada Whirlwind Essence Clutch:",
    details: " Capture the essence of a whirlwind with the Prada Whirlwind Essence Clutch. The dynamic design and vibrant details make it a playful and energetic accessory. This clutch is a burst of energy in your fashion repertoire.",
    price: " Price:$550",
},
// prada ends

    // chanel starts
    {
        id: 121,
        imgSrc: './assets/chanel/c1.png',
        name: "Chanel Velvet Elegance Clutch",
        details: "Indulge in luxury with the Chanel Velvet Elegance Clutch. The plush velvet exterior and iconic Chanel logo make it a statement piece for your evening ensemble. This clutch exudes sophistication and opulence, making it the perfect companion for special occasions.",
        price: "Price:$890",
    },
    {
        id: 122,
        imgSrc: './assets/chanel/c2.jpg',
        name: "Chanel City Lights Crossbody",
        details: "Navigate the urban landscape in style with the Chanel City Lights Crossbody. The compact design and chic quilting showcase Chanel's timeless elegance. This crossbody is a versatile choice for the modern woman on the move.",
        price: "Price:$720",
    },
    {
        id: 123,
        imgSrc: './assets/chanel/c3.jpg',
        name: "Chanel Serenity Satchel Mini",
        details: "Find serenity in style with the Chanel Serenity Satchel Mini. This downsized beauty features the classic Chanel chain strap and quilted pattern, creating an iconic look. Despite its compact size, it offers ample space for your essentials.",
        price: "Price:$950",
    },
    {
        id: 124,
        imgSrc: './assets/chanel/c4.jpg',
        name: "Chanel Urban Chic Shoulder Bag",
        details: "Embrace urban chic with the Chanel Urban Chic Shoulder Bag. The modern design and durable materials make it a practical yet fashionable choice for daily use. This shoulder bag effortlessly combines style and functionality",
        price: "Price:$850",
    },
    {
        id: 125,
        imgSrc: './assets/chanel/c5.jpg',
        name: "Chanel Enchanting Tweed Clutch",
        details: "Unleash your inner enchantress with the Chanel Enchanting Tweed Clutch. The textured tweed and elegant Chanel details make it a whimsical accessory for formal occasions. This clutch is a celebration of timeless charm and sophistication.",
        price: "Price:$980",
    },
    {
        id: 126,
        imgSrc: './assets/chanel/c6.jpg',
        name: "Chanel Modern Muse Tote Mini ",
        details: "Become a modern muse with the Chanel Modern Muse Tote Mini. This downsized tote features the signature Chanel chain handles and a contemporary design. It's perfect for those who appreciate luxury in a compact form.",
        price: "Price:$920",
    },
    {
        id: 127,
        imgSrc: './assets/chanel/c7.png',
        name: "Chanel Quilted Bliss Wallet ",
        details: "Experience quilted bliss with the Chanel Quilted Bliss Wallet. The classic quilting and timeless design make it an essential accessory for the Chanel aficionado. Stay organized with this elegant and practical wallet",
        price: "Price:$650",
    },
    {
        id: 128,
        imgSrc: './assets/chanel/c8.jpg',
        name: "Chanel Pearl Elegance Backpack ",
        details: "Elevate your casual look with the Chanel Pearl Elegance Backpack. The subtle pearl details and quilted pattern add a touch of glamour to this everyday accessory. This backpack is a fusion of luxury and practicality.",
        price: "Price:$980",
    },


    {
        id: 129,
        imgSrc: './assets/chanel/c9.jpg',
        name: "Chanel Velvet Twilight Crossbody",
        details: "Embrace the allure of twilight with the Chanel Velvet Twilight Crossbody. The rich velvet and compact design make it a versatile choice for evening affairs. This crossbody is a subtle yet captivating addition to your ensemble.",
        price: "Price:$780",
    },
    {
        id: 130,
        imgSrc: './assets/chanel/c10.jpg',
        name: "Chanel Essence of Lace Clutch",
        details: " Capture the essence of elegance with the Chanel Essence of Lace Clutch. The delicate lace detailing and compact size make it a romantic choice for various occasions. This clutch is a timeless accessory for the refined woman.",
        price: "Price:$550",
    },
    {
        id: 131,
        imgSrc: './assets/chanel/c11.jpg ',
        name: "Chanel Sublime Suede Satchel",
        details: "Immerse yourself in sublime luxury with the Chanel Sublime Suede Satchel. The rich suede exterior and polished Chanel hardware create an accessory that commands attention. This satchel is a symbol of opulence and sophistication.",
        price: "Price:$960",
    },
    {
        id: 132,
        imgSrc: './assets/chanel/c12.jpg',
        name: "Chanel Midnight Star Crossbody ",
        details: "Shine like a star with the Chanel Midnight Star Crossbody. The celestial details and compact size make it an elegant choice for night time outings. This crossbody is a constellation of style in the vast universe of fashion.",
        price: "Price:$780",
    },
    {
        id: 133,
        imgSrc: './assets/chanel/c13.jpg',
        name: "Chanel Quilted Urban Tote",
        details: "Navigate city life with the Chanel Quilted Urban Tote. The classic quilting and durable materials make it a practical yet stylish choice for daily use. This tote seamlessly blends elegance with functionality.",
        price: "Price:$920 ",
    },
    {
        id: 134,
        imgSrc: './assets/chanel/c14.jpg',
        name: "Chanel Pearlized Elegance Wallet",
        details: "Indulge in pearlized elegance with the Chanel Pearlized Elegance Wallet. The subtle pearl details and compact design make it a sophisticated addition to your daily essentials. This wallet is a timeless accessory for the modern woman.",
        price: "Price:$650",
    },
    {
        id: 135,
        imgSrc: './assets/chanel/c15.jpg',
        name: "Chanel Enigma Explorer Backpack",
        details: "Unravel the enigma of fashion with the Chanel Enigma Explorer Backpack. The mysterious design and adjustable straps make it an intriguing choice for day or night. This backpack is a puzzle of style waiting to be solved.",
        price: "Price:$890 ",
    },
    {
        id: 136,
        imgSrc: './assets/chanel/c16.jpg',
        name: " Chanel Refined Elegance Tote",
        details: "Reach the pinnacle of style with the Chanel Refined Elegance Tote. The structured design and premium materials create an accessory that commands attention. Versatile and chic, it's an essential for the modern woman on the go.",
        price: "Price:$840",
    },
    {
        id: 137,
        imgSrc: './assets/chanel/c17.jpg',
        name: "Chanel Celestial Dreams Clutch",
        details: "Drift into celestial dreams with the Chanel Celestial Dreams Clutch. The cosmic details and compact form make it a whimsical addition to your evening ensemble. This clutch is a touch of otherworldly elegance.",
        price: "Price:$620",
    },

    {
        id: 138,
        imgSrc: './assets/chanel/c18.jpg',
        name: "Chanel Whimsical Petals Crossbody",
        details: "Carry a bouquet of style with the Chanel Whimsical Petals Crossbody. The floral details and compact size make it a delightful accessory for various occasions. This crossbody is a garden of elegance in the world of fashion.",
        price: "Price:$880",
    },
    {
        id: 139,
        imgSrc: './assets/chanel/c19.jpg',
        name: "Chanel Urban Verve Elegance",
        details: "Infuse your style with urban verve using the Chanel Urban Verve Elegance. The sleek design and premium materials create an accessory that exudes confidence and sophistication. Elevate your look with this embodiment of city chic.",
        price: "Price:$980",
    },
    {
        id: 140,
        imgSrc: './assets/chanel/c20.jpg',
        name: "Chanel Mirage Dreams Tote",
        details: "Chase your dreams with the Chanel Mirage Dreams Tote. The dreamy design and spacious interior make it a practical yet whimsical choice. This tote is a work of art for the modern woman.",
        price: "Price:$840",
    },
    {
        id: 141,
        imgSrc: './assets/chanel/c21.png',
        name: "Chanel Urban Edge Velvet Clutch",
        details: "Embrace the urban edge with the Chanel Urban Edge Velvet Clutch. The combination of plush velvet and modern design makes it a standout accessory. Perfect for evenings out, this clutch exudes sophistication and contemporary allure.",
        price: "Price:$950",
    },
    {
        id: 142,
        imgSrc: './assets/chanel/c22.jpg',
        name: "Chanel Evening Sparkle Crossbody",
        details: "Add a touch of sparkle to your evening ensemble with the Chanel Evening Sparkle Crossbody. The shimmering details and compact size make it an ideal choice for special occasions. This crossbody is a dazzling accessory for a night on the town.",
        price: "Price:$780",
    },
    {
        id: 143,
        imgSrc: './assets/chanel/c23.jpg',
        name: "Chanel Nouveau Chic Satchel Mini",
        details: "Embody nouveau chic with the Chanel Nouveau Chic Satchel Mini. This downsized satchel features Chanel's signature quilting and timeless elegance. Despite its smaller size, it remains a classic statement piece for any fashion enthusiast.",
        price: "Price:$890",
    },


    {
        id: 144,
        imgSrc: './assets/chanel/c24.jpg',
        name: "Chanel Metropolitan Elegance Tote",
        details: "Navigate the city in style with the Chanel Metropolitan Elegance Tote. The modern design and durable materials make it a practical yet chic choice for daily use. This tote seamlessly blends urban sophistication with timeless allure.",
        price: "Price:$920",
    },
    {
        id: 145,
        imgSrc: './assets/chanel/c25.jpg',
        name: "Chanel Enchanted Tweed Wallet",
        details: "Carry a touch of enchantment with the Chanel Enchanted Tweed Wallet. The textured tweed and classic Chanel detailing make it an essential accessory for everyday luxury. This wallet is a charming addition to your fashion repertoire.",
        price: "Price:$620 ",
    },
    {
        id: 146,
        imgSrc: './assets/chanel/c26.jpg',
        name: "Chanel Velvet Noir Explorer Backpack",
        details: "Explore the city with the Chanel Velvet Noir Explorer Backpack. The rich velvet and spacious compartments create a luxurious yet functional accessory. This backpack is a symbol of urban elegance and versatility",
        price: "Price:$980",
    },
    {
        id: 147,
        imgSrc: './assets/chanel/c27.png',
        name: "Chanel Ethereal Lace Crossbody Bliss",
        details: "Experience ethereal charm with the Chanel Ethereal Lace Crossbody Bliss. The delicate lace detailing and adjustable strap make it a graceful and versatile choice. This crossbody is a touch of otherworldly elegance for your daily adventures.",
        price: "Price:$880 ",
    },
    {
        id: 148,
        imgSrc: './assets/chanel/c28.jpg',
        name: "Chanel Pinnacle Pearl Elegance",
        details: "Reach the pinnacle of style with the Chanel Pinnacle Pearl Elegance. The subtle pearl details and structured design create an accessory that commands attention. Versatile and chic, it's an essential for the modern woman with refined taste.",
        price: "Price:$940",
    },
    {
        id: 149,
        imgSrc: './assets/chanel/c29.jpg',
        name: "Chanel Celestial Voyager Tote",
        details: "Embark on a celestial journey with the Chanel Celestial Voyager Tote. The cosmic details and spacious interior make it a whimsical yet practical choice. This tote is a piece of art for the woman who dreams beyond the stars.",
        price: "Price:$860",
    },

    {
        id: 150,
        imgSrc: './assets/chanel/c30.jpg',
        name: "Chanel Sublime Suede Clutch",
        details: "Immerse yourself in sublime luxury with the Chanel Sublime Suede Clutch. The rich suede exterior and polished Chanel hardware create an accessory that stands out in sophistication. This clutch is a symbol of opulence and timeless style. ",
        price: "Price:$940",
    },
    {
        id: 151,
        imgSrc: './assets/chanel/c31.jpg',
        name: "Chanel Radiant Starlight Crossbody",
        details: "Shine like a radiant star with the Chanel Radiant Starlight Crossbody. The celestial details and compact size make it an elegant choice for nighttime outings. This crossbody is a constellation of style in the vast universe of fashion.",
        price: "Price:$780",
    },
    {
        id: 152,
        imgSrc: './assets/chanel/c32.jpg',
        name: "Chanel Luxe Affair Quilted Tote",
        details: "Indulge in a luxe affair with the Chanel Luxe Affair Quilted Tote. The exquisite craftsmanship and iconic quilting make it a standout accessory. This tote is a celebration of opulence and timeless sophistication.",
        price: "Price:$920",
    },
    {
        id: 153,
        imgSrc: './assets/chanel/c33.jpg',
        name: "Chanel Whispering Petals Velvet Clutch",
        details: "Carry the beauty of whispering petals with the Chanel Whispering Petals Velvet Clutch. The floral details and plush velvet make it a delightful accessory for various occasions. This clutch is a garden of elegance in the world of fashion",
        price: "Price:$650",
    },
    {
        id: 154,
        imgSrc: './assets/chanel/c34.png',
        name: "Chanel Celestial Dreams Wallet",
        details: "Drift into celestial dreams with the Chanel Celestial Dreams Wallet. The cosmic details and compact form make it a whimsical yet practical addition to your daily essentials. This wallet is a touch of otherworldly elegance for the modern woman.",
        price: "Price:$620",
    },
    {
        id: 155,
        imgSrc: './assets/chanel/c35.jpg',
        name: "Chanel Enigma Explorer Satchel",
        details: "Unravel the enigma of fashion with the Chanel Enigma Explorer Satchel. The mysterious design and timeless elegance make it an intriguing choice. This satchel is a puzzle of style waiting to be solved.",
        price: "price:$910",
    },
    {
        id: 156,
        imgSrc: './assets/chanel/c36.jpg',
        name: "Chanel Refined Elegance Velvet Clutch",
        details: "Elevate your evening look with the Chanel Refined Elegance Velvet Clutch. The plush velvet and sophisticated design make it a standout accessory. This clutch is a symbol of opulence and contemporary allure.",
        price: "Price:$780",
    },
    {
        id: 157,
        imgSrc: './assets/chanel/c37.jpg',
        name: "Chanel Ethereal Lace Urban Tote",
        details: "Embrace ethereal charm with the Chanel Ethereal Lace Urban Tote. The delicate lace details and durable materials make it a practical yet whimsical choice for daily use. This tote is a touch of otherworldly elegance for the modern woman.",
        price: "Price:$860",
    },
    {
        id: 158,
        imgSrc: './assets/chanel/c38.jpg',
        name: "Chanel Celestial Voyager Wallet",
        details: "Carry the cosmos with the Chanel Celestial Voyager Wallet. The celestial details and compact form make it a whimsical yet practical accessory. This wallet is a piece of art for the woman who dreams beyond the stars.",
        price: "Price:$620",
    },

    {
        id: 159,
        imgSrc: './assets/chanel/c39.jpg',
        name: "Chanel Sublime Suede Voyager Backpack",
        details: "Explore the city in sublime style with the Chanel Sublime Suede Voyager Backpack. The rich suede and spacious compartments create a luxurious yet functional accessory. This backpack is a symbol of opulence and urban versatility.",
        price: "Price:$940",
    },
    {
        id: 160,
        imgSrc: './assets/chanel/c40.jpg',
        name: "Chanel Urban Pearlized Elegance Crossbody",
        details: "Infuse your urban look with pearlized elegance using the Chanel Urban Pearlized Elegance Crossbody. The sleek design and subtle pearl details create an accessory that exudes confidence and sophistication. Elevate your style with this embodiment of city chic",
        price: "Price:$880 ",
    },
    // chanel ends 

   // fendi starts
   {
    id: 161,
    imgSrc: './assets/fendi/f1.png',
    name: "Fendi Velvet Luxe Clutch",
    details: "Indulge in luxury with the Fendi Velvet Luxe Clutch. The plush velvet exterior and iconic Fendi logo make it a statement piece for your evening ensemble. This clutch exudes sophistication and opulence, making it the perfect companion for special occasions.",
    price: " Price:$950",
},
{
    id: 162,
    imgSrc: './assets/fendi/f2.png',
    name: "Fendi Urban Explorer Crossbody",
    details: "Navigate the urban landscape in style with the Fendi Urban Explorer Crossbody. The compact design and distinctive Fendi detailing showcase the brand's timeless elegance. This crossbody is a versatile choice for the modern woman on the move.",
    price: " Price:$780",
},
{
    id: 163,
    imgSrc: './assets/fendi/f3.jpg',
    name: "Fendi Serenity Mini Satchel",
    details: "Find serenity in style with the Fendi Serenity Mini Satchel. This downsized beauty features the classic Fendi FF logo pattern, creating an iconic look. Despite its compact size, it offers ample space for your essentials.",
    price: " Price:$920",
},
{
    id: 164,
    imgSrc: './assets/fendi/f4.jpg',
    name: "Fendi Metropolitan Elegance Tote",
    details: "Navigate the city in style with the Fendi Metropolitan Elegance Tote. The modern design and durable materials make it a practical yet chic choice for daily use. This tote seamlessly blends urban sophistication with timeless allure.",
    price: " Price:$850",
},
{
    id: 165,
    imgSrc: './assets/fendi/f5.png',
    name: "Fendi Enchanted Tweed Clutch",
    details: "Unleash your inner enchantress with the Fendi Enchanted Tweed Clutch. The textured tweed and elegant Fendi details make it a whimsical accessory for formal occasions. This clutch is a celebration of timeless charm and sophistication.",
    price: " Price:$980",
},
{
    id: 166,
    imgSrc: './assets/fendi/f6.png',
    name: "Fendi Modern Muse Mini Tote",
    details: "Become a modern muse with the Fendi Modern Muse Mini Tote. This downsized tote features the iconic Fendi logo pattern and a contemporary design. It's perfect for those who appreciate luxury in a compact form.",
    price: " Price:$920",
},
{
    id: 167,
    imgSrc: './assets/fendi/f7.jpg',
    name: "Fendi Quilted Bliss Wallet",
    details: "Experience quilted bliss with the Fendi Quilted Bliss Wallet. The classic quilting and timeless design make it an essential accessory for the Fendi enthusiast. Stay organized with this elegant and practical wallet.",
    price: " Price:$650",
},

{
    id: 168,
    imgSrc: './assets/fendi/f8.jpg',
    name: "Fendi Velvet Noir Explorer Backpack",
    details: "Explore the city with the Fendi Velvet Noir Explorer Backpack. The rich velvet and spacious compartments create a luxurious yet functional accessory. This backpack is a symbol of urban elegance and versatility.",
    price: " Price:$980",
},
{
    id: 169,
    imgSrc: './assets/fendi/f9.png',
    name: "Fendi Celestial Bliss Crossbody",
    details: "Experience celestial bliss with the Fendi Celestial Bliss Crossbody. The cosmic details and compact size make it an elegant choice for nighttime outings. This crossbody is a constellation of style in the vast universe of fashion.",
    price: " Price:$780",
},
{
    id: 170,
    imgSrc: './assets/fendi/f10.png',
    name: "Fendi Urban Verve Clutch",
    details: "Infuse your style with urban verve using the Fendi Urban Verve Clutch. The sleek design and premium materials create an accessory that exudes confidence and sophistication. Elevate your look with this embodiment of city chic.",
    price: " Price:$550",
},
{
    id: 171,
    imgSrc: './assets/fendi/f11.png',
    name: "Fendi Sublime Suede Satchel",
    details: "Immerse yourself in sublime luxury with the Fendi Sublime Suede Satchel. The rich suede exterior and polished Fendi hardware create an accessory that commands attention. This satchel is a symbol of opulence and sophistication.",
    price: " Price:$960",
},
{
    id: 172,
    imgSrc: './assets/fendi/f12.jpg',
    name: "Fendi Starlight Bliss Crossbody",
    details: "Shine like a star with the Fendi Starlight Bliss Crossbody. The celestial details and compact size make it an elegant choice for night time outings. This crossbody is a constellation of style in the vast universe of fashion.",
    price: " Price:$780",
},
{
    id: 173,
    imgSrc: './assets/fendi/f13.png',
    name: "Fendi Luxe Affair Quilted Tote",
    details: "Indulge in a luxe affair with the Fendi Luxe Affair Quilted Tote. The exquisite craftsmanship and iconic quilting make it a standout accessory. This tote is a celebration of opulence and timeless sophistication.",
    price: " Price:$920",
},
{
    id: 174,
    imgSrc: './assets/fendi/f14.jpg',
    name: "Fendi Whispering Petals Velvet Clutch",
    details: "Carry the beauty of whispering petals with the Fendi Whispering Petals Velvet Clutch. The floral details and plush velvet make it a delightful accessory for various occasions. This clutch is a garden of elegance in the world of fashion.",
    price: " Price:$650",
},
{
    id: 175,
    imgSrc: './assets/fendi/f15.png',
    name: "Fendi Celestial Voyager Wallet",
    details: "Carry the cosmos with the Fendi Celestial Voyager Wallet. The celestial details and compact form make it a whimsical yet practical accessory. This wallet is a piece of art for the woman who dreams beyond the stars.",
    price: " Price:$620",
},
{
    id: 176,
    imgSrc: './assets/fendi/f16.png',
    name: "Fendi Refined Elegance Clutch",
    details: "Elevate your evening look with the Fendi Refined Elegance Clutch. The sleek design and premium materials make it a standout accessory. This clutch is a symbol of opulence and contemporary allure.",
    price: " Price:$780",
},

{
    id: 177,
    imgSrc: '/assets/fendi/f17.jpg',
    name: "Fendi Ethereal Lace Urban Tote",
    details: "Embrace ethereal charm with the Fendi Ethereal Lace Urban Tote. The delicate lace details and durable materials make it a practical yet whimsical choice for daily use. This tote is a touch of otherworldly elegance for the modern woman.",
    price: " Price:$860",
},
{
    id: 178,
    imgSrc: './assets/fendi/f18.png',
    name: "Fendi Sublime Suede Voyager Backpack",
    details: "Explore the city in sublime style with the Fendi Sublime Suede Voyager Backpack. The rich suede and spacious compartments create a luxurious yet functional accessory. This backpack is a symbol of opulence and urban versatility.",
    price: " Price:$940",
},
{
    id: 179,
    imgSrc: './assets/fendi/f19.jpg',
    name: "Fendi Urban Pearlized Elegance Crossbody",
    details: "Infuse your urban look with pearlized elegance using the Fendi Urban Pearlized Elegance Crossbody. The sleek design and subtle pearl details create an accessory that exudes confidence and sophistication. Elevate your style with this embodiment of city chic.",
    price: " Price:$880",
},
{
    id: 180,
    imgSrc: './assets/fendi/f20.png',
    name: "Fendi Celestial Dreams Voyager Tote",
    details: "Embark on a celestial journey with the Fendi Celestial Dreams Voyager Tote. The cosmic details and spacious interior make it a whimsical yet practical choice. This tote is a piece of art for the woman who dreams beyond the stars.",
    price: " Price:$860",
},
{
    id: 181,
    imgSrc: './assets/fendi/f21.png',
    name: "Fendi Enchanted Blossom Clutch",
    details: "Unveil the magic of fashion with the Fendi Enchanted Blossom Clutch. The delicate floral details and compact size make it a whimsical choice for formal occasions. This clutch is a celebration of natural beauty and sophistication.",
    price: " Price:$950",
},
{
    id: 182,
    imgSrc: './assets/fendi/f22.jpg',
    name: "Fendi Urban Voyager Mini Backpack",
    details: "Navigate the city streets with the Fendi Urban Voyager Mini Backpack. The compact size and iconic Fendi pattern make it a stylish companion for your daily adventures. This mini backpack is a symbol of urban chic and functionality",
    price: " Price:$890",
},
{
    id: 183,
    imgSrc: './assets/fendi/f23.jpg',
    name: "Fendi Quilted Serenity Wallet",
    details: "Experience tranquility in style with the Fendi Quilted Serenity Wallet. The classic quilting and compact design make it an essential accessory for everyday luxury. This wallet is a perfect blend of sophistication and practicality.",
    price: " Price:$650",
},
{
    id: 184,
    imgSrc: './assets/fendi/f24.jpg',
    name: "Fendi Pearlized Elegance Crossbody",
    details: "Elevate your ensemble with the Fendi Pearlized Elegance Crossbody. The subtle pearl details and sleek design create an accessory that exudes confidence and sophistication. This crossbody is a symbol of refined urban style.",
    price: " Price:$880",
},
{
    id: 185,
    imgSrc: './assets/fendi/f25.png',
    name: "Fendi Cosmic Dreams Tote",
    details: "Dream beyond the stars with the Fendi Cosmic Dreams Tote. The celestial details and spacious interior make it a whimsical yet practical choice. This tote is a piece of art for the woman who aspires to reach new heights in fashion.",
    price: " Price:$840",
},
{
    id: 186,
    imgSrc: './assets/fendi/f26.png',
    name: "Fendi Velvet Essence Satchel",
    details: "Immerse yourself in the plush luxury of the Fendi Velvet Essence Satchel. The rich velvet exterior and timeless design make it a standout accessory. This satchel is a symbol of opulence and classic sophistication.",
    price: " Price:$920",
},
{
    id: 187,
    imgSrc: './assets/fendi/f27.jpg',
    name: "Fendi Ethereal Lace Bliss Crossbody",
    details: "Experience ethereal charm with the Fendi Ethereal Lace Bliss Crossbody. The delicate lace detailing and adjustable strap make it a graceful and versatile choice. This crossbody is a touch of otherworldly elegance for your daily adventures.",
    price: " Price:$780",
},
{
    id: 188,
    imgSrc: './assets/fendi/f28.jpg',
    name: "Fendi Urban Icon Mini Clutch",
    details: "Infuse your look with urban icon status using the Fendi Urban Icon Mini Clutch. The sleek design and premium materials create an accessory that exudes confidence and modern sophistication. Elevate your style with this mini clutch.",
    price: " Price:$550",
},

{
    id: 189,
    imgSrc: './assets/fendi/f29.png',
    name: "Fendi Metropolitan Luxe Wallet",
    details: "Navigate the city in luxe style with the Fendi Metropolitan Luxe Wallet. The modern design and compact form make it a whimsical yet practical accessory. This wallet is a symbol of urban elegance for the modern woman.",
    price: " Price:$620",
},
{
    id: 190,
    imgSrc: './assets/fendi/f30.png',
    name: "Fendi Velvet Dream Explorer Backpack",
    details: "Explore your fashion dreams with the Fendi Velvet Dream Explorer Backpack. The rich velvet and spacious compartments create a luxurious yet functional accessory. This backpack is a symbol of opulence and dreamy urban style.",
    price: " Price:$980",
},
{
    id: 191,
    imgSrc: './assets/fendi/f31.jpg',
    name: "Fendi Quilted Bliss Mini Clutch",
    details: "Carry elegance in the palm of your hand with the Fendi Quilted Bliss Mini Clutch. The classic quilting and compact size make it a sophisticated addition to your ensemble. This mini clutch is a celebration of timeless style.",
    price: " Price:$780",
},

{
    id: 192,
    imgSrc: './assets/fendi/f32.jpg',
    name: "Fendi Whimsical Petals Voyager Tote",
    details: "Carry a garden of style with the Fendi Whimsical Petals Voyager Tote. The floral details and spacious interior make it a delightful yet practical choice. This tote is a burst of elegance in the world of fashion.",
    price: " Price:$860",
},
{
    id: 193,
    imgSrc: './assets/fendi/f33.png',
    name: "Fendi Serenity Bliss Wallet",
    details: "Find serenity in your daily essentials with the Fendi Serenity Bliss Wallet. The compact design and classic Fendi detailing make it an essential accessory. This wallet is a perfect blend of sophistication and tranquillity.",
    price: " Price:$620",
},
{
    id: 194,
    imgSrc: './assets/fendi/f34.jpg',
    name: "Fendi Urban Velvet Explorer Backpack",
    details: "Explore the city streets with the Fendi Urban Velvet Explorer Backpack. The rich velvet and spacious compartments create a luxurious yet functional accessory. This backpack is a symbol of opulence and urban versatility.",
    price: " Price:$980",
},
{
    id: 195,
    imgSrc: './assets/fendi/f35.png',
    name: "Fendi Velvet Starlight Clutch",
    details: "Shine like a star with the Fendi Velvet Starlight Clutch. The celestial details and plush velvet make it an elegant choice for evening affairs. This clutch is a constellation of style in the vast universe of fashion.",
    price: " Price:$650",
},

{
    id: 196,
    imgSrc: './assets/fendi/f36.jpg',
    name: "Fendi Pearlized Elegance Bliss Crossbody",
    details: "Carry urban sophistication with the Fendi Pearlized Elegance Bliss Crossbody. The sleek design and subtle pearl details create an accessory that exudes confidence and modern style. Elevate your look with this crossbody.",
    price: " Price:$880",
},
{
    id: 197,
    imgSrc: './assets/fendi/f37.png',
    name: "Fendi Ethereal Lace Mini Clutch",
    details: "Experience ethereal charm in a compact form with the Fendi Ethereal Lace Mini Clutch. The delicate lace detailing and compact size make it a graceful addition to your ensemble. This mini clutch is a touch of otherworldly elegance.",
    price: " Price:$780",
},
{
    id: 198,
    imgSrc: './assets/fendi/f38.png',
    name: "Fendi Urban Icon Wallet",
    details: "Infuse your daily essentials with urban icon status using the Fendi Urban Icon Wallet. The modern design and compact form make it a whimsical yet practical accessory. This wallet is a symbol of urban elegance for the modern woman.",
    price: " Price:$620",
},
{
    id: 199,
    imgSrc: './sunblockimages/kidsskincareproducts.jpg',
    name: "Fendi Starry Dreams Voyager Tote",
    details: "Carry the dreams of the night sky with the Fendi Starry Dreams Voyager Tote. The celestial details and spacious interior make it a whimsical yet practical choice. This tote is a piece of art for the woman who aspires to reach for the stars.",
    price: " Price:$860",
},
{
    id: 200,
    imgSrc: './assets/fendi/f40.png',
    name: "Fendi Velvet Elegance Bliss Crossbody",
    details: "Experience elegance in every detail with the Fendi Velvet Elegance Bliss Crossbody. The plush velvet and sleek design create an accessory that exudes confidence and sophistication. This crossbody is a celebration of opulence and modern style.",
    price: " Price:$780",
},
    // fendi ends

    // aldo starts
    {
        id: 201,
        imgSrc: './assets/aldo/a1.png',
        name: "Aldo Velvet Dream Clutch",
        details: "Immerse yourself in the plush luxury of the Aldo Velvet Dream Clutch. The rich velvet exterior and compact design make it a standout accessory. This clutch is a symbol of opulence and modern sophistication",
        price: "Price:$950",
    },

    {
        id: 202,
        imgSrc: './assets/aldo/a2.png',
        name: "Aldo Urban Chic Mini Tote",
        details: "Infuse your look with urban chic using the Aldo Urban Chic Mini Tote. The sleek design and durable materials create an accessory that exudes confidence and contemporary style. Elevate your ensemble with this mini tote.",
        price: " Price:$750",
    },
    {
        id: 203,
        imgSrc: './assets/aldo/a3.png',
        name: "Aldo Serene Elegance Satchel",
        details: "Find serenity in style with the Aldo Serene Elegance Satchel. This downsized beauty features a timeless silhouette and meticulous detailing. Despite its smaller size, it remains a classic statement piece for any fashion enthusiast.",
        price: " Price:$920",
    },
    {
        id: 204,
        imgSrc: './assets/aldo/a4.png',
        name: "Aldo Metropolitan Explorer Backpack",
        details: "Navigate the city in style with the Aldo Metropolitan Explorer Backpack. The modern design and spacious compartments make it a practical yet chic choice for daily use. This backpack seamlessly blends urban sophistication with timeless allure.",
        price: "Price:$880",
    },
    {
        id: 205,
        imgSrc: './assets/aldo/a5.jpg',
        name: "Aldo Enchanted Blossom Crossbody",
        details: "Unveil the magic of fashion with the Aldo Enchanted Blossom Crossbody. The delicate floral details and compact size make it a whimsical choice for various occasions. This crossbody is a celebration of natural beauty and sophistication.",
        price: " Price:$650",
    },
    {
        id: 206,
        imgSrc: './assets/aldo/a6.png',
        name: "Aldo Modern Muse Wallet",
        details: "Become a modern muse with the Aldo Modern Muse Wallet. The contemporary design and compact form make it a whimsical yet practical addition to your daily essentials. This wallet is a perfect blend of sophistication and style. ",
        price: " Price:$520",
    },
    {
        id: 207,
        imgSrc: './assets/aldo/a7.png',
        name: "Aldo Quilted Bliss Mini Clutch",
        details: "Carry elegance in the palm of your hand with the Aldo Quilted Bliss Mini Clutch. The classic quilting and compact size make it a sophisticated addition to your ensemble. This mini clutch is a celebration of timeless style.",
        price: " Price:$780",
    },
    {
        id: 208,
        imgSrc: './assets/aldo/a8.png',
        name: "Aldo Pearlized Elegance Crossbody",
        details: "Elevate your ensemble with the Aldo Pearlized Elegance Crossbody. The subtle pearl details and sleek design create an accessory that exudes confidence and sophistication. This crossbody is a symbol of refined urban style.",
        price: "Price:$880",
    },
    {
        id: 209,
        imgSrc: './assets/aldo/a9.png',
        name: "Aldo Celestial Dreams Tote",
        details: "Dream beyond the stars with the Aldo Celestial Dreams Tote. The celestial details and spacious interior make it a whimsical yet practical choice. This tote is a piece of art for the woman who aspires to reach new heights in fashion.",
        price: " Price:$840",
    },
    {
        id: 210,
        imgSrc: './assets/aldo/a10.png',
        name: "Aldo Refined Elegance Clutch",
        details: "Elevate your evening look with the Aldo Refined Elegance Clutch. The sleek design and premium materials make it a standout accessory. This clutch is a symbol of opulence and contemporary allure.",
        price: " Price:$780",
    },
    {
        id: 211,
        imgSrc: './assets/aldo/a11.png',
        name: "Aldo Whispering Petals Voyager Tote",
        details: "Carry a garden of style with the Aldo Whispering Petals Voyager Tote. The floral details and spacious interior make it a delightful yet practical choice. This tote is a burst of elegance in the world of fashion.",
        price: " Price:$860",
    },
    {
        id: 212,
        imgSrc: './assets/aldo/a12.png',
        name: "Aldo Ethereal Lace Mini Clutch",
        details: "Experience ethereal charm in a compact form with the Aldo Ethereal Lace Mini Clutch. The delicate lace detailing and compact size make it a graceful addition to your ensemble. This mini clutch is a touch of otherworldly elegance.",
        price: " Price:$680",
    },
    {
        id: 213,
        imgSrc: './assets/aldo/a13.png',
        name: "Aldo Urban Icon Wallet",
        details: "Infuse your daily essentials with urban icon status using the Aldo Urban Icon Wallet. The modern design and compact form make it a whimsical yet practical accessory. This wallet is a symbol of urban elegance for the modern woman.",
        price: " Price:$550",
    },
    {
        id: 214,
        imgSrc: './assets/aldo/a14.jpg',
        name: "Aldo Starry Dreams Voyager Tote",
        details: "Carry the dreams of the night sky with the Aldo Starry Dreams Voyager Tote. The celestial details and spacious interior make it a whimsical yet practical choice. This tote is a piece of art for the woman who aspires to reach for the stars.",
        price: " Price:$800",
    },
    {
        id: 215,
        imgSrc: './assets/aldo/a15.png',
        name: "Aldo Velvet Elegance Bliss Crossbody",
        details: "Experience elegance in every detail with the Aldo Velvet Elegance Bliss Crossbody. The plush velvet and sleek design create an accessory that exudes confidence and sophistication. This crossbody is a celebration of opulence and modern style.",
        price: " Price:$720",
    },
    {
        id: 216,
        imgSrc: './assets/aldo/a16.png',
        name: "Aldo Pearlized Essence Wallet",
        details: "Infuse your daily essentials with pearlized essence using the Aldo Pearlized Essence Wallet. The subtle pearl details and compact design make it a sophisticated addition to your routine. This wallet is a symbol of refined urban style.",
        price: " Price:$580",
    },
    {
        id: 217,
        imgSrc: './assets/aldo/a17.png',
        name: "Aldo Celestial Voyager Mini Backpack",
        details: "Navigate the city streets with the Aldo Celestial Voyager Mini Backpack. The compact size and celestial details make it a stylish companion for your daily adventures. This mini backpack is a symbol of dreamy urban style.",
        price: " Price:$820",
    },
    {
        id: 218,
        imgSrc: './assets/aldo/a18.png',
        name: "Aldo Luxe Affair Quilted Tote",
        details: "Indulge in a luxe affair with the Aldo Luxe Affair Quilted Tote. The exquisite craftsmanship and iconic quilting make it a standout accessory. This tote is a celebration of opulence and timeless sophistication.",
        price: " Price:$920",
    },
    {
        id: 219,
        imgSrc: './assets/aldo/a19.jpg',
        name: "Aldo Velvet Essence Bliss Crossbody",
        details: "Immerse yourself in the plush luxury of the Aldo Velvet Essence Bliss Crossbody. The rich velvet and sleek design create an accessory that exudes confidence and sophistication. This crossbody is a symbol of opulence and modern style.",
        price: " Price:$750",
    },
    {
        id: 220,
        imgSrc: './assets/aldo/a20.png',
        name: "Aldo Ethereal Dreams Clutch",
        details: "Drift into ethereal dreams with the Aldo Ethereal Dreams Clutch. The dreamy design and compact size make it a whimsical yet practical accessory. This clutch is a touch of otherworldly elegance for the modern woman.Absolutely! Here are 20 more unique and detailed descriptions for Aldo purses with different names and prices below $1000",
        price: " Price:$680",
    },
    {
        id: 221,
        imgSrc: './assets/aldo/a21.png',
        name: "Aldo Urban Elegance Satchel",
        details: "Embrace urban elegance with the Aldo Urban Elegance Satchel. The modern silhouette and meticulous detailing make it a versatile companion for any occasion. This satchel is a blend of sophistication and contemporary style.",
        price: " Price:$980",
    },
    {
        id: 222,
        imgSrc: './assets/aldo/a22.png',
        name: "Aldo Celestial Bliss Mini Clutch",
        details: "Experience celestial bliss with the Aldo Celestial Bliss Mini Clutch. The cosmic details and compact size make it an elegant choice for nighttime outings. This mini clutch is a constellation of style in the vast universe of fashion.",
        price: " Price:$650",
    },
    {
        id: 223,
        imgSrc: './assets/aldo/a23.png',
        name: "Aldo Velvet Starlight Crossbody",
        details: "Shine like a star with the Aldo Velvet Starlight Crossbody. The celestial details and plush velvet make it a sophisticated choice for evening affairs. This crossbody is a constellation of style in the vast universe of fashion.",
        price: " Price:$850",
    },
    {
        id: 224,
        imgSrc: './assets/aldo/a24.png',
        name: "Aldo Whimsical Petals Wallet",
        details: "Carry the beauty of whispering petals with the Aldo Whimsical Petals Wallet. The floral details and compact design make it a delightful accessory for various occasions. This wallet is a garden of elegance in the world of fashion.",
        price: " Price:$500",
    },
    {
        id: 225,
        imgSrc: './assets/aldo/a25.png',
        name: "Aldo Urban Icon Mini Tote",
        details: "Infuse your look with urban icon status using the Aldo Urban Icon Mini Tote. The sleek design and premium materials create an accessory that exudes confidence and modern sophistication. Elevate your style with this mini tote.",
        price: " Price:$750",
    },
    {
        id: 226,
        imgSrc: './assets/aldo/a26.png',
        name: "Aldo Pearlized Elegance Bliss Crossbody",
        details: "Carry urban sophistication with the Aldo Pearlized Elegance Bliss Crossbody. The sleek design and subtle pearl details create an accessory that exudes confidence and modern style. Elevate your look with this crossbody.",
        price: " Price:$880",
    },

    {
        id: 227,
        imgSrc: './assets/aldo/a27.png',
        name: "Aldo Ethereal Lace Voyager Tote",
        details: "Embark on an ethereal journey with the Aldo Ethereal Lace Voyager Tote. The delicate lace details and spacious interior make it a whimsical yet practical choice. This tote is a touch of otherworldly elegance for the modern woman.",
        price: " Price:$900",
    },

    {
        id: 228,
        imgSrc: './assets/aldo/a28.png',
        name: "Aldo Sublime Suede Clutch",
        details: "Immerse yourself in sublime luxury with the Aldo Sublime Suede Clutch. The rich suede exterior and compact design make it a standout accessory. This clutch is a symbol of opulence and sophistication.",
        price: " Price:$950",
    },

    {
        id: 229,
        imgSrc: './assets/aldo/a29.png',
        name: "Aldo Starry Dreams Mini Backpack",
        details: "Carry the dreams of the night sky with the Aldo Starry Dreams Mini Backpack. The celestial details and compact size make it a whimsical yet practical choice. This mini backpack is a piece of art for the woman who aspires to reach for the stars.",
        price: " Price:$820",
    },
    {
        id: 230,
        imgSrc: './assets/aldo/a30.png',
        name: "Aldo Velvet Essence Bliss Wallet",
        details: "Experience elegance in every detail with the Aldo Velvet Essence Bliss Wallet. The plush velvet and sleek design create an accessory that exudes confidence and sophistication. This wallet is a celebration of opulence and modern style.",
        price: " Price:$580",
    },
    {
        id: 231,
        imgSrc: './assets/aldo/a31.png',
        name: "Aldo Enchanted Tweed Voyager Tote",
        details: "Unleash your inner enchantress with the Aldo Enchanted Tweed Voyager Tote. The textured tweed and elegant Aldo details make it a whimsical accessory for various occasions. This tote is a celebration of timeless charm and sophistication.",
        price: " Price:$920",
    },

    {
        id: 232,
        imgSrc: './assets/aldo/a32.png',
        name: "Aldo Urban Verve Clutch",
        details: "Infuse your style with urban verve using the Aldo Urban Verve Clutch. The sleek design and premium materials create an accessory that exudes confidence and sophistication. Elevate your look with this embodiment of city chic.",
        price: " Price:$600",
    },

    {
        id: 233,
        imgSrc: './assets/aldo/a33.png',
        name: "Aldo Velvet Dream Mini Clutch",
        details: "Immerse yourself in the plush luxury of the Aldo Velvet Dream Mini Clutch. The rich velvet and compact design make it a standout accessory. This mini clutch is a symbol of opulence and modern sophistication.",
        price: "Price:$720",
    },

    {
        id: 234,
        imgSrc: './assets/aldo/a34.png',
        name: "Aldo Metropolitan Elegance Wallet",
        details: "Navigate the city in luxe style with the Aldo Metropolitan Elegance Wallet. The modern design and compact form make it a whimsical yet practical accessory. This wallet is a symbol of urban elegance for the modern woman.",
        price: " Price:$620",
    },

    {
        id: 235,
        imgSrc: './assets/aldo/a35.png',
        name: "Aldo Whispering Petals Bliss Crossbody",
        details: "Carry the beauty of whispering petals with the Aldo Whispering Petals Bliss Crossbody. The floral details and compact size make it a delightful yet practical choice. This crossbody is a garden of elegance in the world of fashion.",
        price: " Price:$700",
    },

    {
        id: 236,
        imgSrc: './assets/aldo/a36.png',
        name: "Aldo Celestial Voyager Mini Clutch",
        details: "Experience celestial bliss with the Aldo Celestial Voyager Mini Clutch. The cosmic details and compact size make it an elegant choice for nighttime outings. This mini clutch is a constellation of style in the vast universe of fashion.",
        price: " Price:$580",
    },

    {
        id: 237,
        imgSrc: './assets/aldo/a37.png',
        name: "Aldo Refined Elegance Satchel",
        details: "Elevate your ensemble with the Aldo Refined Elegance Satchel. The sleek design and premium materials make it a standout accessory. This satchel is a symbol of opulence and contemporary allure.",
        price: "Price:$880",
    },

    {
        id: 238,
        imgSrc: './assets/aldo/a38.png',
        name: "Aldo Urban Explorer Mini Tote",
        details: "Navigate the urban landscape in style with the Aldo Urban Explorer Mini Tote. The compact design and distinctive Aldo detailing showcase the brand's timeless elegance. This mini tote is a versatile choice for the modern woman on the move.",
        price: " Price:$700",
    },

    {
        id: 239,
        imgSrc: './assets/aldo/a39.png',
        name: "Aldo Ethereal Dreams Wallet",
        details: "Drift into ethereal dreams with the Aldo Ethereal Dreams Wallet. The dreamy design and compact form make it a whimsical yet practical accessory. This wallet is a touch of otherworldly elegance for the modern woman.",
        price: " Price:$550",
    },

    {
        id: 240,
        imgSrc: './assets/aldo/a40.png',
        name: "Aldo Sublime Suede Bliss Crossbody",
        details: "Carry elegance in every detail with the Aldo Sublime Suede Bliss Crossbody. The rich suede and sleek design create an accessory that exudes confidence and sophistication. This crossbody is a celebration of opulence and modern style.",
        price: " Price:$780",
    },
    // aldo ends
]


getTrainerData();

function getTrainerData() {

    let id = getId();

    if (id == null) {
        id = 1;
    }

    trainerData.map((item) => {
        if (item.id == id) {
            document.getElementById('productImg').src = item.imgSrc;
            document.getElementById('name').innerText = item.name;
            document.getElementById('details').innerText = item.details;
            document.getElementById('price').innerText = item.price;

            // document.getElementById('trainerImg').src = item.imgSrc;
            // document.getElementById('specialties-container').innerText = item.specialize;
        }
    })

}